#!/bin/bash
# sanitize-exposed-secrets.sh
# Automated secret rotation and git history scrubbing
# Generated by: Lola Security Audit 2026-03-25
# REQUIRES: Manual coordination with Manu before Phase 2 (history scrubbing)

set -e  # Exit on error

WORKSPACE="$HOME/.openclaw/workspace"
BACKUP_DIR="$HOME/emergency-backups"
TIMESTAMP=$(date +%Y%m%d-%H%M)

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ============================================================================
# PHASE 1: BACKUP & PREPARATION
# ============================================================================

phase1_backup() {
    log_info "Phase 1: Creating emergency backup..."
    
    mkdir -p "$BACKUP_DIR"
    
    cd "$WORKSPACE"
    
    # Stash any uncommitted changes
    if ! git diff-index --quiet HEAD --; then
        log_warn "Uncommitted changes detected, stashing..."
        git stash save "Pre-sanitization stash $TIMESTAMP"
    fi
    
    # Create full backup
    tar czf "$BACKUP_DIR/pre-sanitization-$TIMESTAMP.tar.gz" \
        --exclude='.git' \
        --exclude='node_modules' \
        .
    
    log_info "Backup created: $BACKUP_DIR/pre-sanitization-$TIMESTAMP.tar.gz"
    log_info "File count: $(tar tzf "$BACKUP_DIR/pre-sanitization-$TIMESTAMP.tar.gz" | wc -l)"
}

# ============================================================================
# PHASE 2: SECRET ROTATION (Manual - Instructions Only)
# ============================================================================

phase2_rotation_instructions() {
    log_warn "Phase 2: Secret Rotation - MANUAL STEPS REQUIRED"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo "  🔑 SECRET ROTATION INSTRUCTIONS"
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "1️⃣  Google OAuth Client Secret:"
    echo "   a. Go to: https://console.cloud.google.com/apis/credentials"
    echo "   b. Project: optimal-courage-486312-c8"
    echo "   c. Find OAuth 2.0 Client → Download NEW client_secret.json"
    echo "   d. Run: gog auth credentials ~/Downloads/client_secret_NEW.json"
    echo "   e. Test: gog gmail search 'is:unread' --max 1"
    echo "   f. Revoke old secret in Google Cloud Console"
    echo ""
    echo "2️⃣  Anthropic OAuth Token:"
    echo "   a. Go to: https://console.anthropic.com/settings/keys"
    echo "   b. Create New Key"
    echo "   c. Update: nano ~/.openclaw/.env"
    echo "      Replace: ANTHROPIC_API_KEY=sk-ant-NEW_KEY"
    echo "   d. Test: curl -X POST https://api.anthropic.com/v1/messages \\"
    echo "            -H 'x-api-key: \$ANTHROPIC_API_KEY' \\"
    echo "            -H 'anthropic-version: 2023-06-01' \\"
    echo "            -H 'content-type: application/json' \\"
    echo "            -d '{\"model\":\"claude-sonnet-4-5\",\"messages\":[{\"role\":\"user\",\"content\":\"test\"}],\"max_tokens\":10}'"
    echo "   e. Revoke old key in console.anthropic.com"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    
    read -p "Have you completed BOTH rotations? (yes/no): " confirm
    if [ "$confirm" != "yes" ]; then
        log_error "Secret rotation not confirmed. Exiting."
        exit 1
    fi
    
    log_info "Secret rotation confirmed. Proceeding..."
}

# ============================================================================
# PHASE 3: FILE REMOVAL & REDACTION
# ============================================================================

phase3_remove_files() {
    log_info "Phase 3: Removing sensitive files from workspace..."
    
    cd "$WORKSPACE"
    
    # Remove client_secret.json
    if [ -f "temp/client_secret.json" ]; then
        log_warn "Removing: temp/client_secret.json"
        rm temp/client_secret.json
    else
        log_info "temp/client_secret.json already removed"
    fi
    
    # Redact token from memory file
    log_info "Redacting Anthropic token from memory/subscription-vs-api-analysis.md"
    if [ -f "memory/subscription-vs-api-analysis.md" ]; then
        sed -i.bak 's/sk-ant-oat01[^ ]*/[ANTHROPIC_TOKEN_REDACTED]/g' memory/subscription-vs-api-analysis.md
        rm memory/subscription-vs-api-analysis.md.bak
    fi
    
    # Update .gitignore
    log_info "Updating .gitignore..."
    cat >> .gitignore << 'EOF'

# ===== SECRETS & CREDENTIALS (Added 2026-03-25) =====
temp/*secret*
**/client_secret*.json
**/.env
**/.env.*
**/credentials.json
**/token.json
**/*_secret.*
**/*-secret.*
**/api_keys.txt
**/*.pem
**/*.key
!**/*.pub.key
**/*oauth*.json
!**/oauth-example.json
EOF
    
    # Commit changes
    git add .gitignore memory/subscription-vs-api-analysis.md
    git commit -m "🔒 Security: Remove exposed secrets, enhance gitignore

- Removed temp/client_secret.json (Google OAuth secret)
- Redacted Anthropic token from memory file
- Enhanced .gitignore with comprehensive secret patterns
- Audit: SECURITY-SECRETS-AUDIT-2026-03-25.md

Ref: Security audit by Lola (2026-03-25)"
    
    log_info "Files removed and changes committed"
}

# ============================================================================
# PHASE 4: GIT HISTORY SCRUBBING
# ============================================================================

phase4_scrub_history() {
    log_warn "Phase 4: Git History Scrubbing - DESTRUCTIVE OPERATION"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo "  ⚠️  WARNING: GIT HISTORY REWRITE"
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "This will:"
    echo "  • Remove temp/client_secret.json from ALL commits"
    echo "  • Replace secret values with [REDACTED] in history"
    echo "  • Rewrite git history (requires force-push)"
    echo ""
    echo "Prerequisites:"
    echo "  • BFG Repo-Cleaner installed (brew install bfg)"
    echo "  • OR git-filter-repo (pip3 install git-filter-repo)"
    echo "  • Coordination with Manu for force-push"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    
    read -p "Proceed with history scrubbing? (yes/no): " confirm
    if [ "$confirm" != "yes" ]; then
        log_warn "History scrubbing skipped. Secrets still in git history!"
        return
    fi
    
    cd "$WORKSPACE"
    
    # Check if BFG is available
    if command -v bfg &> /dev/null; then
        log_info "Using BFG Repo-Cleaner (recommended)..."
        
        # Delete file from history
        bfg --delete-files client_secret.json --no-blob-protection
        
        # Replace secret strings
        cat > /tmp/bfg-replacements.txt << 'EOF'
***REDACTED***-RFYFN6l5u84_wySc9==>[GOOGLE_SECRET_REDACTED]
sk-ant-oat01==>[ANTHROPIC_TOKEN_REDACTED]
EOF
        bfg --replace-text /tmp/bfg-replacements.txt
        rm /tmp/bfg-replacements.txt
        
        # Cleanup
        git reflog expire --expire=now --all
        git gc --prune=now --aggressive
        
        log_info "BFG scrubbing complete"
        
    elif command -v git-filter-repo &> /dev/null; then
        log_info "Using git-filter-repo..."
        
        # Remove file
        git filter-repo --path temp/client_secret.json --invert-paths --force
        
        # Replace strings
        cat > /tmp/filter-repo-replacements.txt << 'EOF'
literal:***REDACTED***-RFYFN6l5u84_wySc9==>[GOOGLE_SECRET_REDACTED]
regex:sk-ant-oat01[^ ]*==>[ANTHROPIC_TOKEN_REDACTED]
EOF
        git filter-repo --replace-text /tmp/filter-repo-replacements.txt --force
        rm /tmp/filter-repo-replacements.txt
        
        log_info "git-filter-repo scrubbing complete"
        
    else
        log_error "Neither BFG nor git-filter-repo found!"
        echo ""
        echo "Install one of:"
        echo "  • BFG: brew install bfg (macOS) or download from rtyley.github.io/bfg-repo-cleaner/"
        echo "  • git-filter-repo: pip3 install git-filter-repo"
        exit 1
    fi
    
    log_info "Git history scrubbed successfully"
}

# ============================================================================
# PHASE 5: PREVENTION SETUP
# ============================================================================

phase5_prevention() {
    log_info "Phase 5: Setting up secret prevention..."
    
    cd "$WORKSPACE"
    
    # Check if git-secrets is available
    if ! command -v git-secrets &> /dev/null; then
        log_warn "git-secrets not installed"
        echo "Install with:"
        echo "  • macOS: brew install git-secrets"
        echo "  • Linux: https://github.com/awslabs/git-secrets"
        echo ""
        read -p "Skip git-secrets setup? (yes/no): " skip
        if [ "$skip" != "yes" ]; then
            exit 1
        fi
    else
        log_info "Installing git-secrets hooks..."
        
        # Initialize git-secrets
        git secrets --install -f || true
        git secrets --register-aws || true
        
        # Add custom patterns
        git secrets --add 'GOCSPX-[A-Za-z0-9_-]+' || true  # Google OAuth
        git secrets --add 'sk-ant-[A-Za-z0-9]+' || true    # Anthropic
        git secrets --add 'sk-proj-[A-Za-z0-9]+' || true   # OpenAI
        git secrets --add 'ghp_[A-Za-z0-9]+' || true       # GitHub token
        git secrets --add 'AIza[A-Za-z0-9_-]+' || true     # Google API
        
        log_info "git-secrets pre-commit hook installed"
        
        # Test hook
        echo "sk-ant-test123" > /tmp/test-secret.txt
        cp /tmp/test-secret.txt "$WORKSPACE/test-secret-check.txt"
        git add test-secret-check.txt
        
        if git commit -m "test secret detection" 2>&1 | grep -q "prohibited"; then
            log_info "✅ Pre-commit hook working correctly (blocked test secret)"
            git reset HEAD test-secret-check.txt
            rm test-secret-check.txt /tmp/test-secret.txt
        else
            log_warn "⚠️  Pre-commit hook may not be working"
        fi
    fi
    
    log_info "Prevention setup complete"
}

# ============================================================================
# PHASE 6: VERIFICATION
# ============================================================================

phase6_verification() {
    log_info "Phase 6: Verifying sanitization..."
    
    cd "$WORKSPACE"
    
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo "  🔍 VERIFICATION CHECKS"
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    
    # Check 1: Secrets in workspace
    echo "1️⃣  Checking for secrets in workspace files..."
    secret_count=$(rg "***REDACTED***-RFYFN6l5u84_wySc9" . 2>/dev/null | wc -l)
    if [ "$secret_count" -eq 0 ]; then
        log_info "✅ No Google OAuth secret found in workspace"
    else
        log_error "❌ Google OAuth secret still in workspace ($secret_count occurrences)"
    fi
    
    anthropic_count=$(rg "sk-ant-oat01[^ ]*" . 2>/dev/null | grep -v "REDACTED" | wc -l)
    if [ "$anthropic_count" -eq 0 ]; then
        log_info "✅ No Anthropic token found in workspace (or redacted)"
    else
        log_warn "⚠️  Anthropic token pattern found ($anthropic_count occurrences)"
    fi
    
    # Check 2: Secrets in git history
    echo ""
    echo "2️⃣  Checking for secrets in git history..."
    git_secret_count=$(git log -S "***REDACTED***-RFYFN6l5u84_wySc9" --all 2>/dev/null | wc -l)
    if [ "$git_secret_count" -eq 0 ]; then
        log_info "✅ No Google OAuth secret in git history"
    else
        log_error "❌ Google OAuth secret still in git history ($git_secret_count commits)"
    fi
    
    git_anthropic_count=$(git log -S "sk-ant-oat01" --all 2>/dev/null | wc -l)
    if [ "$git_anthropic_count" -eq 0 ]; then
        log_info "✅ No Anthropic token in git history"
    else
        log_warn "⚠️  Anthropic token pattern in git history ($git_anthropic_count commits)"
    fi
    
    # Check 3: .gitignore
    echo ""
    echo "3️⃣  Checking .gitignore..."
    if grep -q "client_secret.*\.json" .gitignore; then
        log_info "✅ .gitignore includes secret patterns"
    else
        log_warn "⚠️  .gitignore may not include all patterns"
    fi
    
    # Check 4: Pre-commit hook
    echo ""
    echo "4️⃣  Checking pre-commit hook..."
    if [ -f ".git/hooks/pre-commit" ] && grep -q "git-secrets" .git/hooks/pre-commit; then
        log_info "✅ git-secrets pre-commit hook installed"
    else
        log_warn "⚠️  git-secrets pre-commit hook not detected"
    fi
    
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
}

# ============================================================================
# PHASE 7: FORCE-PUSH COORDINATION
# ============================================================================

phase7_force_push() {
    log_warn "Phase 7: Force-Push Coordination"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo "  🚨 FORCE-PUSH REQUIRED"
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "Git history has been rewritten locally."
    echo "To update remote repository, run:"
    echo ""
    echo "  git push origin --force --all"
    echo "  git push origin --force --tags"
    echo ""
    echo "⚠️  WARNING: This will overwrite remote history."
    echo "   • All collaborators must re-clone"
    echo "   • Open PRs may need rebasing"
    echo "   • Backup is saved in: $BACKUP_DIR"
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    
    read -p "Execute force-push now? (yes/no): " confirm
    if [ "$confirm" = "yes" ]; then
        git push origin --force --all
        git push origin --force --tags
        log_info "Force-push complete"
    else
        log_warn "Force-push skipped. Remember to push manually!"
    fi
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

main() {
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo "  🔒 SECRET SANITIZATION SCRIPT"
    echo "  Generated: 2026-03-25"
    echo "  Auditor: Lola Security Subagent"
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    
    # Confirm before starting
    read -p "Start secret sanitization process? (yes/no): " start
    if [ "$start" != "yes" ]; then
        log_info "Sanitization cancelled"
        exit 0
    fi
    
    # Execute phases
    phase1_backup
    phase2_rotation_instructions
    phase3_remove_files
    phase4_scrub_history
    phase5_prevention
    phase6_verification
    phase7_force_push
    
    echo ""
    echo "════════════════════════════════════════════════════════════════"
    echo "  ✅ SANITIZATION COMPLETE"
    echo "════════════════════════════════════════════════════════════════"
    echo ""
    echo "Summary:"
    echo "  • Secrets rotated (manual)"
    echo "  • Files removed from workspace"
    echo "  • Git history scrubbed"
    echo "  • Prevention mechanisms installed"
    echo "  • Backup saved: $BACKUP_DIR/pre-sanitization-$TIMESTAMP.tar.gz"
    echo ""
    echo "Next steps:"
    echo "  1. Review verification output above"
    echo "  2. Test rotated credentials work"
    echo "  3. Monitor nightly security scans"
    echo "  4. Update audit report: SECURITY-SECRETS-AUDIT-2026-03-25.md"
    echo ""
}

# Run main if executed directly
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    main "$@"
fi
